export const data= [
"Business Services",
"Computers & Internet",
"Events & Conferences",
"Finances & Insurance",
"Food & Drink",
"Legal",
"Manufacturing & Industry",
"Tourism & Accommodation",
"Transport & Motoring",
"Public & Social Services",
"Property",
"Training",
"Advertising",
"Information Technology",
"Communications",
"Computer Services",
"Web Development",
"Investment Companies",
"Leasing",
"Tax Consultants",
"Business Management Consulting",
"Banking Equipment",
"Payroll Services",
"Dept Counseling",
"Others"
]